# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'BTFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for BTFramework
  pod 'AFNetworking', '~>3.1.0'
  pod 'Masonry','~>1.0.2'
  pod 'MBProgressHUD', '~> 1.2.0'
  
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'TPKeyboardAvoiding'
  pod 'MLTransition'
  pod 'FMDB'
  pod 'CocoaAsyncSocket'
  pod 'Shimmer'
  pod 'FlatUIKit'

  pod 'RESideMenu'
  pod 'SWTableViewCell'
  
  
end
